-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE O.PRODUCE_DATE LIKE '2022-05%' AND O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SUM(O.AMOUNT) * P.PRICE DESC, P.PRODUCT_ID ASC;